### ISSUE TITLE
Doesn't work in 1.19.4

### ISSUE THREAD

**Issue by grlndgz** [Roundaround/mc-fabric-shearable-vines#2]
Hey Round, Beagle again.

I just wanted to let you know this hasn't worked for me in 1.19.4. It was fine in 1.19.3.

When I hit the Use Item key (which I have bound to left-alt) nothing happens. There's no shearing noise. It doesn't matter if I have doVinesSpread set to true or false.

I'd much rather you spend your time getting things ready to go for 1.20, but I wanted to let you know in case this affected that in any way.

Thanks!!

**Comment by Roundaround** [comment]
Huh, it's definitely working for me when I load it up in 1.19.4. I even tried rebinding to left alt like you and it still works fine.

Are the vines already sheared? You cannot shear them more than once. You can check in the F3 menu on the right under "Targeted Block". You should see s "sheared" property that'll be true or false.

**Comment by grlndgz** [comment]
Cue DaveGuy saying, oh my god I'm an idiot, I'm an actual idiot.

It works just fine if you put it in the mods folder and not datapacks.

Thanks for looking.
